import Head from "next/head";
import Image from "next/image";
import { FaXTwitter } from "react-icons/fa6";
import { IoIosMailUnread } from "react-icons/io";
import { BsInstagram } from "react-icons/bs";
import { FaFacebook, FaYoutube } from "react-icons/fa";

export default function Home() {
  return (
    <div className="bg-black text-white">
      <Head>
        <title>Kumarghat R.D. Block Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto p-4">
        <div className="text-center">
          <h1 className="text-2xl font-bold mb-4 text-cyan-500">
            Kumarghat RD Block
          </h1>
          <p className="text-sm">Contents owned by Kumarghat RD Block.</p>
        </div>

        <div className="mt-2 text-center">
          <p className="mb-2 text-sm text-amber-600">
            © Kumarghat RD Block, Developed by Kumarghat Block,
          </p>
          <p className="mb-2 text-xs">Goverment Of Tripura.</p>
          <p className="mb-4 text-xs">Last Updated: Jul 10, 2024</p>
        </div>
        <div className="flex justify-center mt-4">
          <ul className="flex gap-4">
            <li>
              <a href="https://www.facebook.com/bdokgt">
                <FaFacebook className="w-8 h-8 hover:text-blue-600" />
              </a>
            </li>
            <li>
              <a href="https://x.com/bdokgt">
                <FaXTwitter className="w-8 h-8 hover:text-gray-800" />
              </a>
            </li>
            <li>
              <a href="https://www.instagram.com/bdokgt/">
                <BsInstagram className="w-8 h-8 hover:text-red-600" />
              </a>
            </li>

            <li>
              <a href="https://www.youtube.com/@bdokgt">
                <FaYoutube className="w-8 h-8 hover:text-red-700" />
              </a>
            </li>
          </ul>
        </div>
      </main>
    </div>
  );
}
